services:
<<<<<<< HEAD
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html/www
      - ./blog:/var/www/html/blog
    networks:
      - webnet
    depends_on:
      - php
  php:
    build:
      context: ./php
    volumes:
      - ./www:/var/www/html/www
    networks:
      - webnet
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
      MYSQL_DATABASE: "woodytoys"
    volumes:
      - maria-db:/var/lib/mysql
      - ./woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
    networks:
      - webnet


volumes:
  maria-db:
networks:
  webnet:
=======
  dns:
    image: dns_serv_v1.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    container_name: dns
    restart: unless-stopped
>>>>>>> 7d0e1a4f84e80459d25ff8a88fe064f1aebffda1
